name: Build, test, and deploy docs

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Zig Setup
        uses: mlugg/setup-zig@v2
      - name: Build and test
        run: zig build test
      - name: Generate docs
        run: zig build-lib -femit-docs src/jwt.zig